INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH) VALUES(1,'HDFC','123456','123456.111111',4,'HDFC');
INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH) VALUES(2,'ICICI','123556','123556.222222',4,'ICICI');
INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH) VALUES(3,'SBI','333331','333331.111111',3,'SBI');

INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE,LOGO_IMAGE,LOGO_FILE_NAME,AUTHENICATION_APP_URL) VALUES(4,'SBI','1234','123556.222222',1,'SBI',null,null,null,null,null,null,null,'http://www.issuerurl.com/login');
INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE,LOGO_IMAGE,LOGO_FILE_NAME,AUTHENICATION_APP_URL) VALUES(5,'HDFC','5678','333331.111111',2,'SBI',null,null,null,null,null,null,null,'http://www.issuerurl1.com/login');

INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE,LOGO_IMAGE,LOGO_FILE_NAME,AUTHENICATION_APP_URL) VALUES(6,'ICICI','9012','123556.222222',3,'SBI',null,null,null,null,null,null,null,'http://www.issuerurl.com/login');
INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE,LOGO_IMAGE,LOGO_FILE_NAME,AUTHENICATION_APP_URL) VALUES(7,'SBI','1145','333331.111111',4,'SBI',null,null,null,null,null,null,null,'http://www.issuerurl.com/login');

INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE,LOGO_IMAGE,LOGO_FILE_NAME,AUTHENICATION_APP_URL) VALUES(8,'HDFC','6678','123556.222222',5,'SBI',null,null,null,null,null,null,null,'http://www.issuerurl.com/login');

INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,123466,'R');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123556,123476,'R');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,123446,'T');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123556,123456,'T');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,153466,'R');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123556,153476,'R');

INSERT INTO BATCH_FILE_TYPES(ID,FILE_NAME,DESCRIPTION) VALUES (1,'PYMNTAUTHCREATE','Creation of Payment Instruments via pre-load');
INSERT INTO BATCH_FILE_TYPES(ID,FILE_NAME,DESCRIPTION) VALUES (2,'SETACCOUNTLOCK','Lock or unlock of Customers account');

INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('google-wallet','1234','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('yahoo-wallet','4566','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('spring-wallet','8089','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('papal-wallet','1233','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('zippy-wallet','6809','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('jpa-wallet','3456','N');

INSERT INTO TOKEN_POS_ENTRY_MODES (ID,ENTRY_MODE,DESCRIPTION) VALUES (1,'1','Hello World');
INSERT INTO TOKEN_POS_ENTRY_MODES (ID,ENTRY_MODE,DESCRIPTION) VALUES (2,'2','Test');

