INSERT INTO CUSTOMERS(ID,USERNAME,HASHED_PASSWORD,PASSWORD_SALT,REGISTRATION_TOKEN,ISSUER_CUSTOMER_ID,LAST_SUCCESSFUL_LOGIN,LAST_FAILED_LOGIN,ACCOUNT_LOCKED,ACCOUNT_LOCKED_REASON_CODE,ACCOUNT_LOCKED_AT,LAST_PASSWORD_CHANGE_DATETIME)
VALUES(1,"John Taylor","1234","12","789","4567",null,null,1,"9",null,null);
INSERT INTO CUSTOMERS(ID,USERNAME,HASHED_PASSWORD,PASSWORD_SALT,REGISTRATION_TOKEN,ISSUER_CUSTOMER_ID,LAST_SUCCESSFUL_LOGIN,LAST_FAILED_LOGIN,ACCOUNT_LOCKED,ACCOUNT_LOCKED_REASON_CODE,ACCOUNT_LOCKED_AT,LAST_PASSWORD_CHANGE_DATETIME)
VALUES(2,"Peter Brokes","12345","12","789","4567",null,null,1,"9",null,null);
INSERT INTO CUSTOMERS(ID,USERNAME,HASHED_PASSWORD,PASSWORD_SALT,REGISTRATION_TOKEN,ISSUER_CUSTOMER_ID,LAST_SUCCESSFUL_LOGIN,LAST_FAILED_LOGIN,ACCOUNT_LOCKED,ACCOUNT_LOCKED_REASON_CODE,ACCOUNT_LOCKED_AT,LAST_PASSWORD_CHANGE_DATETIME)
VALUES(3,"Thomas Paul","12346","12","789","4567",null,null,1,"9",null,null);

INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,123469,'R');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,123459,'R');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,145623,'T');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,146238,'T');

INSERT INTO TOKEN_BIN_MAPPINGS (PAN_BIN_ID, TOKEN_BIN_ID) VALUES(1,1);
INSERT INTO TOKEN_BIN_MAPPINGS (PAN_BIN_ID, TOKEN_BIN_ID) VALUES(2,2);
