package org.tch.ste.domain.entity;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provides Information about Token Requestor ID(Here Wallet Provider) and
 * ARN_ID which will be generated by TCH vault,and information about Wallet
 * instance ID.
 * 
 * @author ramug
 * 
 */
@Entity
@Table(name = "PERMITTED_TOKEN_REQUESTOR_ARNS")
public class PermittedTokenRequestorArn implements Serializable {

    /**
     * Serial version id.
     */
    private static final long serialVersionUID = 3875146790327870752L;

    /**
     * Primary key of Payment Instrument.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID", nullable = false)
    private Integer id;

    @Column(name = "IS_ACTIVE", nullable = false)
    private boolean active;

    /**
     * Arn object for ARN_ID.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ARN_ID", referencedColumnName = "ID")
    private Arn arn;

    /**
     * Token Requestor for Requestor ID.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERMITTED_TOKEN_REQUESTOR_ID", referencedColumnName = "ID")
    private PermittedTokenRequestor permittedTokenRequestor;

    /**
     * List of Permitted Token requestor Arn token.
     */
    @OneToMany(mappedBy = "permittedTokenRequestorArn")
    private List<PermittedTokenRequestorArnToken> permittedTokenRequestorArnsTokens;

    /**
     * Wallet instance ID.
     */
    @Column(name = "CIID", nullable = false)
    private String ciid;

    /**
     * @return the ciid
     */
    public String getCiid() {
        return ciid;
    }

    /**
     * @param ciid
     *            the ciid to set
     */
    public void setCiid(String ciid) {
        this.ciid = ciid;
    }

    /**
     * @return Arn object.
     */
    public Arn getArn() {
        return arn;
    }

    /**
     * @return Primary key.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @return Token Requestor Object.
     */
    public PermittedTokenRequestor getPermittedTokenRequestor() {
        return permittedTokenRequestor;
    }

    /**
     * @return List of Permitted Token Requetor Arn token.
     */
    public List<PermittedTokenRequestorArnToken> getPermittedTokenRequestorArnsTokens() {
        return permittedTokenRequestorArnsTokens;
    }

    /**
     * @param arn
     *            Arn Object.
     */
    public void setArn(Arn arn) {
        this.arn = arn;
    }

    /**
     * @param id
     *            primar key.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @param permittedTokenRequestor
     *            PermittedRequestor object.
     */
    public void setPermittedTokenRequestor(PermittedTokenRequestor permittedTokenRequestor) {
        this.permittedTokenRequestor = permittedTokenRequestor;
    }

    /**
     * @param permittedTokenRequestorArnsTokens
     *            list of permitted token requestor arn tokens.
     */
    public void setPermittedTokenRequestorArnsTokens(
            List<PermittedTokenRequestorArnToken> permittedTokenRequestorArnsTokens) {
        this.permittedTokenRequestorArnsTokens = permittedTokenRequestorArnsTokens;
    }

    /**
     * Returns the field active.
     * 
     * @return active boolean - Get the field.
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the field active.
     * 
     * @param active
     *            boolean - Set the field active.
     */
    public void setActive(boolean active) {
        this.active = active;
    }
}
