INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('Issuer-Hosted w/Real-Time Payment Instrument Provisioning');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('Issuer-Hosted w/Pre-Loaded Payment Instruments');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('TCH-Hosted w/Issuer-Provided Credentials');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('TCH-Hosted w/Generated Credentials');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('TCH-Hosted w/Issuer Auth Web Service');

INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE) VALUES(1,'HDFC','123456','123456.111111',4,'HDFC',3,'HDFC Error.','HDFC Lockout.');
INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,FAILED_LOGINS_TO_LOCKOUT,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE) VALUES(2,'ICICI','123556','123556.222222',4,'ICICI',4,'ICICI Error.','ICICI Lockout.');
INSERT INTO ISSUER_CONFIGURATIONS (ID,ISSUER_NAME,IISN,IID,AUTHENTICATION_TYPE,DROPZONE_PATH,FAILED_LOGINS_TO_LOCKOUT,DISABLE_CREDENTIAL_AFTER_LOGIN,AUTH_ERROR_MESSAGE,AUTH_LOCKOUT_MESSAGE) VALUES(3,'RBS','123656','123556.222222',4,'RBS',4,1,'RBS Error.','RBS Lockout.');

INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED,STATUS_URI_KEY,SUCCESS_URI_VALUE,FAILURE_URI_VALUE) VALUES('HDFC Wallet','123456','N','STATUS','Success','Failure');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED,STATUS_URI_KEY,SUCCESS_URI_VALUE,FAILURE_URI_VALUE) VALUES('ICICI Wallet','123556','N','Status','Succesful','Unsuccessful');

INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID,TOKEN_REQUESTOR_CONFIGURATION_ID) values (1,1);
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID,TOKEN_REQUESTOR_CONFIGURATION_ID) values (2,2);

INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,345345,'R');
INSERT INTO IISN_BINS (IISN, BIN, BIN_TYPE) VALUES(123456,123446,'T');

INSERT INTO TOKEN_POS_ENTRY_MODES (ID,ENTRY_MODE,DESCRIPTION) VALUES (1,'1','Hello World');
INSERT INTO TOKEN_POS_ENTRY_MODES (ID,ENTRY_MODE,DESCRIPTION) VALUES (2,'2','Test');

  
