INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('Issuer-Hosted w/Real-Time Payment Instrument Provisioning');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('Issuer-Hosted w/Pre-Loaded Payment Instruments');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('TCH-Hosted w/Issuer-Provided Credentials');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('TCH-Hosted w/Generated Credentials');
INSERT INTO AUTHENTICATION_MECHANISM (AUTH_MECHANISM) VALUES ('TCH-Hosted w/Issuer Auth Web Service');

INSERT INTO USERS (USER_ID, FIRST_NAME,LAST_NAME,IS_ACTIVE) VALUES ('tch-user-mgmt', 'User','Manager',1);
INSERT INTO USERS (USER_ID, FIRST_NAME,LAST_NAME,IS_ACTIVE) VALUES ('tch-configuration', 'Configuration','Manager',1);
INSERT INTO USERS (USER_ID, FIRST_NAME,LAST_NAME,IISN,IS_ACTIVE) VALUES ('issuer-mgmt', 'Issuer','Manager','123456',1 );
INSERT INTO USERS (USER_ID, FIRST_NAME,LAST_NAME,IS_ACTIVE) VALUES ('unauthorized-issuer', 'Unauthorized','User',1 );

INSERT INTO ROLES (NAME) VALUES('ROLE_TCH_USER_MGMT');
INSERT INTO ROLES (NAME) VALUES('ROLE_TCH_CONFIGURATION');
INSERT INTO ROLES (NAME) VALUES('ROLE_ISSUER_MGMT');
INSERT INTO ROLES (NAME) VALUES('UN_AUTHORIZED');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (4, 4);

INSERT INTO ISSUER_CONFIGURATIONS (ISSUER_NAME,AUTHENTICATION_TYPE,IISN,IID,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,DISABLE_CREDENTIAL_AFTER_LOGIN, FAILED_LOGINS_TO_LOCKOUT, AUTH_ERROR_MESSAGE, AUTH_LOCKOUT_MESSAGE, LOGO_IMAGE,LOGO_FILE_NAME, AUTHENICATION_APP_URL) VALUES('hdfc',3,'123456','567856.123456','/hdfc','2345','1234',1,3,'hdfc data','hdfc data',null,'TEST.JPEG',null);
INSERT INTO ISSUER_CONFIGURATIONS (ISSUER_NAME,AUTHENTICATION_TYPE,IISN,IID,DROPZONE_PATH,AUTH_ENDPOINT,ACCOUNT_LIST_ENDPOINT,DISABLE_CREDENTIAL_AFTER_LOGIN, FAILED_LOGINS_TO_LOCKOUT, AUTH_ERROR_MESSAGE, AUTH_LOCKOUT_MESSAGE, LOGO_IMAGE,LOGO_FILE_NAME, AUTHENICATION_APP_URL) VALUES('icici',4,'123556','567901.123456','/icic','2346','1235',2,4,'icici data','icici data',null,'abc.JPEG',null);
  
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('google-wallet','1234','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('yahoo-wallet','4566','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('spring-wallet','8089','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('papal-wallet','1233','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('zippy-wallet','6809','N');
INSERT INTO TOKEN_REQUESTOR_CONFIGURATIONS (NAME,NETWORK_TR_ID,IS_DELETED) VALUES('jpa-wallet','3456','N');
  
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID) VALUES(1,1);
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID) VALUES(1,2);
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID) VALUES(1,3);
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID) VALUES(1,4);
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID) VALUES(2,4);
INSERT INTO ISSUER_TOKEN_REQUESTORS (ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID) VALUES(2,5);
INSERT INTO ISSUER_TOKEN_REQUESTORS(ISSUER_CONFIGURATION_ID, TOKEN_REQUESTOR_CONFIGURATION_ID)  VALUES(2,6);

INSERT INTO NETWORKS (BIN_FIRST_DIGIT,NAME) VALUES('1','Test1');
INSERT INTO NETWORKS (BIN_FIRST_DIGIT,NAME) VALUES('2','Test2');
