SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE ISSUER_TOKEN_REQUESTORS;
DROP TABLE USERS_ROLES;
DROP TABLE USERS;
DROP TABLE TOKEN_REQUESTOR_CONFIGURATIONS;
DROP TABLE TOKEN_NETWORK_POS_ENTRY_MODE_MAPPING;
DROP TABLE TOKEN_POS_ENTRY_MODES;
DROP TABLE ROLES;
DROP TABLE NETWORKS;
DROP TABLE NETWORK_POS_ENTRY_MODES;
DROP TABLE ISSUER_CONFIGURATIONS;
DROP TABLE IISN_BINS;
DROP TABLE BATCH_FILE_TYPES;
DROP TABLE AUTHENTICATION_MECHANISM;

SET FOREIGN_KEY_CHECKS = 1;