CREATE TABLE ARNS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ARN CHAR(36) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ARN (ARN),
  KEY IDX_ARN_ARN (ARN)
);

CREATE TABLE BATCH_FILE_HISTORIES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BATCH_FILE_TYPE_ID INTEGER NOT NULL,
  PROCESSING_START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PROCESSING_END_TIME TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  SUCCESSFULLY_PROCESSED TINYINT(1) NOT NULL,
  RECORD_COUNT INTEGER NOT NULL,
  BATCH_FILE_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  KEY IDX_BATCHHISTORY_BATCHFILETYPE (BATCH_FILE_TYPE_ID),
  KEY FK_BATCHHISTORY_BATCHFILETYPE (BATCH_FILE_TYPE_ID),
  CONSTRAINT FK_BATCHHISTORY_BATCHFILETYPE FOREIGN KEY (BATCH_FILE_TYPE_ID) REFERENCES BATCH_FILE_TYPES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE CUSTOMERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(15) DEFAULT NULL,
  HASHED_PASSWORD VARCHAR(1000) DEFAULT NULL,
  PASSWORD_SALT VARCHAR(100) DEFAULT NULL,
  REGISTRATION_TOKEN VARCHAR(15) DEFAULT NULL,
  ISSUER_CUSTOMER_ID VARCHAR(15) DEFAULT NULL,
  LAST_SUCCESSFUL_LOGIN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_FAILED_LOGIN TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  ACCOUNT_LOCKED TINYINT(1) DEFAULT NULL,
  ACCOUNT_LOCKED_REASON_CODE CHAR(1) DEFAULT NULL,
  ACCOUNT_LOCKED_AT TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  LAST_PASSWORD_CHANGE_DATETIME TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  FAILED_LOGIN_COUNT INTEGER DEFAULT NULL, 
  PRIMARY KEY (ID),
  UNIQUE KEY USERNAME (USERNAME),
  KEY IDX_CUSTOMERS_ISSUERCUSTID (ISSUER_CUSTOMER_ID),
  KEY IDX_CUSTOMERS_USERNAME (USERNAME)
);

CREATE TABLE LOGIN_HISTORY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INTEGER DEFAULT NULL,
  USERNAME VARCHAR(50) DEFAULT NULL,
  LOGIN_ATTEMPT_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LOGIN_SUCCESSFUL TINYINT(1) NOT NULL,
  ACCOUNT_LOCKED_FROM_FAILED_LOGINS TINYINT(1) NOT NULL,
  ACCOUNT_LOCKED_FROM_SUCCESSFUL_LOGIN TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_LOGINHISTORY_CUSTOMERID (CUSTOMER_ID),
  KEY IDX_LOGINHISTORY_CUSTOMERID (CUSTOMER_ID),
  CONSTRAINT FK_LOGINHISTORY_CUSTOMERID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE PAN_BINS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BIN CHAR(6) NOT NULL,
  TOKEN_EXPIRATION_MINUTES INTEGER NOT NULL,
  TOKEN_EXPIRATION_AMOUNT INTEGER NOT NULL,
  TOKEN_EXPIRATION_USES INTEGER NOT NULL,
  MAX_TOKENS_PER_DAY INTEGER NOT NULL,
  MAX_AMT_FOR_EXPIRED_TOKEN INTEGER NOT NULL,
  MAX_MINUTES_EXPIRED_TOKEN INTEGER NOT NULL,
  PUSH_ON_CREATE TINYINT(1) NOT NULL,
  PULL_ENABLED TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY BIN (BIN),
  KEY IDX_PANBIN_BIN (BIN)
);

CREATE TABLE PAYMENT_INSTRUMENTS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ARN_ID INTEGER NOT NULL,
  CUSTOMER_ID INTEGER DEFAULT NULL,
  PAN_ENCRYPTED VARCHAR(1000) NOT NULL,
  EXP_MONTH_YEAR CHAR(4) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  NICKNAME  VARCHAR(20) DEFAULT NULL,
  ISSUER_ACCOUNT_ID VARCHAR(15) DEFAULT NULL,
  PAN_HASH VARCHAR(1000) NOT NULL,
  PAN_FIRST_SIX_ENCRYPTED VARCHAR(1000) NOT NULL,
  PAN_LAST_FOUR_ENCRYPTED VARCHAR(1000) NOT NULL,
  PAN_LENGTH INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_PAYMENTINSTRUMENT_ARNID (ARN_ID),
  KEY FK_PAYMENTINSTRUMENT_CUSTOMERID (CUSTOMER_ID),
  KEY IDX_PAYMENTINSTRUMENT_ISSUER_ACCOUNT_ID (ISSUER_ACCOUNT_ID),
  CONSTRAINT FK_PAYMENTINSTRUMENT_ARNID FOREIGN KEY (ARN_ID) REFERENCES ARNS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PAYMENTINSTRUMENT_CUSTOMERID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE PERMITTED_TOKEN_REQUESTORS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NETWORK_TR_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY IDX_PERMITTKREQUSTORS_NTTKREQRID (NETWORK_TR_ID)
);

CREATE TABLE PERMITTED_TOKEN_REQUESTOR_ARNS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  PERMITTED_TOKEN_REQUESTOR_ID INTEGER NOT NULL,
  ARN_ID INTEGER NOT NULL,
  CIID VARCHAR(36) DEFAULT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_PERMITTKREQARN_ARNID (ARN_ID),
  KEY FK_PERMITTKREQARN_PERMITTKREQRID (PERMITTED_TOKEN_REQUESTOR_ID),
  KEY IDX_PERMITTKREQARN_ARNID (ARN_ID),
  KEY IDX_PERMITTKREQARN_PERMITTKREQRID (PERMITTED_TOKEN_REQUESTOR_ID),
  CONSTRAINT FK_PERMITTKREQARN_ARNID FOREIGN KEY (ARN_ID) REFERENCES ARNS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PERMITTKREQARN_PERMITTKREQRID FOREIGN KEY (PERMITTED_TOKEN_REQUESTOR_ID) REFERENCES PERMITTED_TOKEN_REQUESTORS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE TOKEN_BINS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BIN CHAR(6) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY BIN (BIN),
  KEY IDX_TKBIN_BIN (BIN)
);

CREATE TABLE TOKEN_BIN_MAPPINGS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  PAN_BIN_ID INTEGER NOT NULL,
  TOKEN_BIN_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_TKBINMAP_PANBINID (PAN_BIN_ID),
  KEY FK_TKBINMAP_TKBINID (TOKEN_BIN_ID),
  KEY IDX_TKBINMAP_PANBINID (PAN_BIN_ID),
  KEY IDX_TKBINMAP_TKBINID (TOKEN_BIN_ID),
  CONSTRAINT FK_TKBINMAP_PAN_BIN FOREIGN KEY (PAN_BIN_ID) REFERENCES IISN_BINS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TKBINMAP_TOKEN_BIN FOREIGN KEY (TOKEN_BIN_ID) REFERENCES TOKEN_BINS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE TOKEN_HISTORIES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  TOKEN_PAN_ENCRYTPED VARCHAR(1000) NOT NULL,
  TOKEN_EXP_MONTH_YEAR CHAR(4) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  EXPIRED_AT TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PAYMENT_INSTRUMENT_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_TKHISTORY_PAYINSTID (PAYMENT_INSTRUMENT_ID),
  KEY IDX_TKHISTORY_PAYINSTID (PAYMENT_INSTRUMENT_ID),
  CONSTRAINT FK_TKHISTORY_PAYINSTID FOREIGN KEY (PAYMENT_INSTRUMENT_ID) REFERENCES PAYMENT_INSTRUMENTS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE TOKENS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  TOKEN_PAN_ENCRYPTED VARCHAR(1000) NOT NULL,
  TOKEN_EXP_MONTH_YEAR CHAR(4) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  EXPECTED_TOKEN_POS_ENTRY_MODE INTEGER NOT NULL,
  TOKEN_PAN_HASH VARCHAR(1000) NOT NULL,
  TOKEN_PAN_FIRST_SIX_ENCRYPTED VARCHAR(1000) NOT NULL,
  TOKEN_PAN_LAST_FOUR_ENCRYPTED VARCHAR(1000) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_TOKENS_TKPOSENTMODID (EXPECTED_TOKEN_POS_ENTRY_MODE),
  CONSTRAINT FK_TOKENS_TKPOSENTMODID FOREIGN KEY (EXPECTED_TOKEN_POS_ENTRY_MODE) REFERENCES TOKEN_POS_ENTRY_MODES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE DETOKENIZATION_REQUESTS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  TOKEN_ID INTEGER NOT NULL,
  CUSTOMER_ID VARCHAR(15) NOT NULL,
  REQUEST_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  WAS_SUCCESSFUL TINYINT(1) NOT NULL,
  NETWORK_TR_ID CHAR(11) NOT NULL,
  TOKEN_PAN_ENCRYPTED VARCHAR(1000) DEFAULT NULL,
  TOKEN_EXP_MONTH_YEAR CHAR(4) DEFAULT NULL,
  TOKEN_PAN_HASH VARCHAR(1000) DEFAULT NULL,
  TOKEN_PAN_FIRST_SIX CHAR(6) DEFAULT NULL,
  TOKEN_PAN_LAST_FOUR CHAR(4) DEFAULT NULL,
  FAILURE_REASON_CODE CHAR(2) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_DETKREQUESTS_TOKENID (TOKEN_ID),
  CONSTRAINT FK_DETKREQUESTS_TOKENID FOREIGN KEY (TOKEN_ID) REFERENCES TOKENS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE DETOKENIZATION_REPORT_HISTORIES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  DETOKENIZATION_REQUEST_ID INTEGER NOT NULL,
  IISN VARCHAR(6) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_DETKREQUESTS_ID (ID),
  CONSTRAINT FK_DETKRPTHIS_DETKREQ_ID FOREIGN KEY (DETOKENIZATION_REQUEST_ID) REFERENCES DETOKENIZATION_REQUESTS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE PERMITTED_TOKEN_REQUESTOR_ARNS_TOKENS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  PERMITTED_TOKEN_REQUESTOR_ARN_ID INTEGER NOT NULL,
  TOKEN_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_PERMITTKREQARNTK_TKARNID (PERMITTED_TOKEN_REQUESTOR_ARN_ID),
  KEY FK_PERMITTKREQARNTK_TOKEN (TOKEN_ID),
  KEY IDX_PERMITTKREQARNTK_TKARNID (PERMITTED_TOKEN_REQUESTOR_ARN_ID),
  KEY IDX_PERMITTKREQARNTK_TOKEN (TOKEN_ID),
  CONSTRAINT FK_PERMITTKREQARNTK_TKARNID FOREIGN KEY (PERMITTED_TOKEN_REQUESTOR_ARN_ID) REFERENCES PERMITTED_TOKEN_REQUESTOR_ARNS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PERMITTKREQARNTK_TOKEN FOREIGN KEY (TOKEN_ID) REFERENCES TOKENS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);