CREATE TABLE AUTHENTICATION_MECHANISM (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  AUTH_MECHANISM VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID_UNIQUE (ID),
  UNIQUE KEY AUTH_MECHANISM_UNIQUE (AUTH_MECHANISM)
);

CREATE TABLE BATCH_FILE_TYPES (
  ID INTEGER NOT NULL,
  FILE_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY FILE_NAME (FILE_NAME),
  KEY IDX_BATCHFT_FILENAME (FILE_NAME)
);

CREATE TABLE IISN_BINS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  IISN CHAR(6) NOT NULL,
  BIN CHAR(6) NOT NULL,
  BIN_TYPE CHAR(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY BIN (BIN),
  KEY IDX_IISN_BIN_BIN (BIN),
  KEY IDX_IISN_BIN_IISN (IISN),
  KEY IDX_IISN_BIN_BIN_TYPE (BIN_TYPE)
);

CREATE TABLE ISSUER_CONFIGURATIONS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ISSUER_NAME VARCHAR(100) NOT NULL,
  AUTHENTICATION_TYPE SMALLINT(6) NOT NULL,
  IISN CHAR(6) NOT NULL,
  IID CHAR(13) NOT NULL,
  DROPZONE_PATH VARCHAR(255) NOT NULL,
  AUTH_ENDPOINT VARCHAR(255) DEFAULT NULL,
  ACCOUNT_LIST_ENDPOINT VARCHAR(255) DEFAULT NULL,
  DISABLE_CREDENTIAL_AFTER_LOGIN TINYINT(1) DEFAULT NULL,
  FAILED_LOGINS_TO_LOCKOUT INTEGER DEFAULT NULL,
  AUTH_ERROR_MESSAGE VARCHAR(1000) DEFAULT NULL,
  AUTH_LOCKOUT_MESSAGE VARCHAR(1000) DEFAULT NULL,
  LOGO_IMAGE BLOB,
  LOGO_FILE_NAME VARCHAR(255) DEFAULT NULL,
  AUTHENICATION_APP_URL VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY IISN (IISN),
  KEY IDX_ISSCONF_IISN (IISN),
  KEY IDX_ISSCONF_ISSUER_NAME (ISSUER_NAME)
);

CREATE TABLE NETWORK_POS_ENTRY_MODES (
  ID INTEGER NOT NULL,
  ENTRY_MODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ENTRY_MODE (ENTRY_MODE),
  KEY IDX_NTPEM_ENTRYMODE (ENTRY_MODE)
);

CREATE TABLE NETWORKS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BIN_FIRST_DIGIT CHAR(1) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY BIN_FIRST_DIGIT (BIN_FIRST_DIGIT),
  KEY IDX_NETWORKS_BFD (BIN_FIRST_DIGIT)
);

CREATE TABLE ROLES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TOKEN_POS_ENTRY_MODES (
  ID INTEGER NOT NULL,
  ENTRY_MODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ENTRY_MODE (ENTRY_MODE),
  KEY IDX_TKPEM_ENTRYMODE (ENTRY_MODE)
);

CREATE TABLE TOKEN_NETWORK_POS_ENTRY_MODE_MAPPING (
  ID INTEGER NOT NULL,
  TOKEN_POS_ENTRY_MODE_ID INTEGER NOT NULL,
  NETWORK_POS_ENTRY_MODE_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY NETWORK_POS_ENTRY_MODE_ID (NETWORK_POS_ENTRY_MODE_ID),
  KEY FK_TNPEMMAP_NTMODEID (NETWORK_POS_ENTRY_MODE_ID),
  KEY FK_TNPEMMAP_TKMODEID (TOKEN_POS_ENTRY_MODE_ID),
  KEY IDX_TKNPEMMAP_NTMODEID (NETWORK_POS_ENTRY_MODE_ID),
  KEY IDX_TKNPEMMAP_TKMODEID (TOKEN_POS_ENTRY_MODE_ID),
  CONSTRAINT FK_TKNPEMMAP_NTMODEID FOREIGN KEY (NETWORK_POS_ENTRY_MODE_ID) REFERENCES NETWORK_POS_ENTRY_MODES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TKNPEMMAP_TKMODEID FOREIGN KEY (TOKEN_POS_ENTRY_MODE_ID) REFERENCES TOKEN_POS_ENTRY_MODES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE TOKEN_REQUESTOR_CONFIGURATIONS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  NETWORK_TR_ID CHAR(11) NOT NULL,
  IS_DELETED CHAR(1) NOT NULL,
  STATUS_URI_KEY VARCHAR(50),
  SUCCESS_URI_VALUE VARCHAR(50),
  FAILURE_URI_VALUE VARCHAR(50),
  PRIMARY KEY (ID),
  KEY IDX_TKRCONF_NTTRID (NETWORK_TR_ID)
);

CREATE TABLE USERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_ID VARCHAR(20) NOT NULL,
  IISN CHAR(6) DEFAULT NULL,
  LAST_LOGIN_TIME TIMESTAMP NULL DEFAULT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  IS_ACTIVE TINYINT(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY USER_ID (USER_ID),
  KEY IDX_USERS_USERID (USER_ID)
);

CREATE TABLE USERS_ROLES (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_USER_ROLE_ROLEID (ROLE_ID),
  KEY FK_USER_ROLE_USERID (USER_ID),
  KEY IDX_USERROLE_USERID (USER_ID),
  CONSTRAINT FK_USER_ROLE_ROLEID FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_ROLE_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE ISSUER_TOKEN_REQUESTORS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ISSUER_CONFIGURATION_ID INTEGER NOT NULL,
  TOKEN_REQUESTOR_CONFIGURATION_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_ISSUERTRMAP_ISSUERID (ISSUER_CONFIGURATION_ID),
  KEY FK_ISSUERTRMAP_TKREQRID (TOKEN_REQUESTOR_CONFIGURATION_ID),
  CONSTRAINT FK_ISSUERTRMAP_ISSUERID FOREIGN KEY (ISSUER_CONFIGURATION_ID) REFERENCES ISSUER_CONFIGURATIONS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ISSUERTRMAP_TKREQRID FOREIGN KEY (TOKEN_REQUESTOR_CONFIGURATION_ID) REFERENCES TOKEN_REQUESTOR_CONFIGURATIONS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);