SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE PERMITTED_TOKEN_REQUESTOR_ARNS_TOKENS;
DROP TABLE DETOKENIZATION_REPORT_HISTORIES;
DROP TABLE DETOKENIZATION_REQUESTS;
DROP TABLE TOKENS;
DROP TABLE TOKEN_HISTORIES;
DROP TABLE TOKEN_BIN_MAPPINGS;
DROP TABLE TOKEN_BINS;
DROP TABLE PERMITTED_TOKEN_REQUESTOR_ARNS;
DROP TABLE PERMITTED_TOKEN_REQUESTORS;
DROP TABLE PAYMENT_INSTRUMENTS;
DROP TABLE PAN_BINS;
DROP TABLE LOGIN_HISTORY;
DROP TABLE CUSTOMERS;
DROP TABLE BATCH_FILE_HISTORIES;
DROP TABLE ARNS;

SET FOREIGN_KEY_CHECKS = 1;